apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: ray-pipeline-job-v2
  namespace: ray
spec:
  entrypoint: "python ray_pipeline.py"

  runtimeEnvYAML: |
    env_vars:
      SUPPLYCHAIN_DATA_S1_PATH: "gs://ray-platform-v2-ray2-data-bucket/supplychain.csv"
      FINANCIAL_DATA_S2_PATH: "gs://ray-platform-v2-ray2-data-bucket/financial.csv"

  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 300

  rayClusterSpec:
    rayVersion: "2.9.0"
    headGroupSpec:
      serviceType: ClusterIP
      rayStartParams:
        num-cpus: "1"
        object-store-memory: "134217728"
      template:
        spec:
          serviceAccountName: ray-head-sa-v2
          nodeSelector:
            node-role: system
          containers:
            - name: ray-head
              # PLACEHOLDER – CI will replace this with built image
              image: "asia-south1-docker.pkg.dev/ray-platform-v2/ray-repo-v2/ray-pipeline-v2@sha256:d64f08a2ae17de3bba2f12c14d07be58f23d67c85ba50b73579553a3d31b264c"
              env:
                - name: SUPPLYCHAIN_DATA_S1_PATH
                  value: "gs://ray-platform-v2-ray2-data-bucket/data/SupplyChain_Data_S1.csv"
                - name: FINANCIAL_DATA_S2_PATH
                  value: "gs://ray-platform-v2-ray2-data-bucket/data/Financial_Data_S2.csv"
                - name: LLM_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: llm-api-secret-v2
                      key: LLM_API_KEY
              resources:
                requests:
                  cpu: "200m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"

    workerGroupSpecs:
      - groupName: workers
        replicas: 1
        minReplicas: 0
        maxReplicas: 5
        rayStartParams:
          num-cpus: "1"
          resources: '"{\"entity_resolver\": 1}"'
        template:
          spec:
            serviceAccountName: ray-worker-sa-v2
            tolerations:
              - key: "ray-worker"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
            containers:
              - name: ray-worker
                image: "asia-south1-docker.pkg.dev/ray-platform-v2/ray-repo-v2/ray-pipeline-v2@sha256:d64f08a2ae17de3bba2f12c14d07be58f23d67c85ba50b73579553a3d31b264c"
                env:
                  - name: SUPPLYCHAIN_DATA_S1_PATH
                    value: "gs://ray-platform-v2-ray2-data-bucket/data/SupplyChain_Data_S1.csv"
                  - name: FINANCIAL_DATA_S2_PATH
                    value: "gs://ray-platform-v2-ray2-data-bucket/data/Financial_Data_S2.csv"
                  - name: LLM_API_KEY
                    valueFrom:
                      secretKeyRef:
                        name: llm-api-secret-v2
                        key: LLM_API_KEY
                resources:
                  requests:
                    cpu: "200m"
                    memory: "256Mi"
                  limits:
                    cpu: "500m"
                    memory: "512Mi"
