apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-head-sa-v2
  namespace: ray
  annotations:
    iam.gke.io/gcp-service-account: ray-head-sa-v2@ray-platform-v2.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-worker-sa-v2
  namespace: ray
  annotations:
    iam.gke.io/gcp-service-account: ray-worker-sa-v2@ray-platform-v2.iam.gserviceaccount.com